### ISSUE TITLE
Logging exception stack trace

### ISSUE THREAD

**Issue by georgeyanev** [gnieh/logback-journal#12]
Is it possible to log the exception stack trace in the journal? There is such a possibility in [log4j-systemd-journal-appender](https://github.com/bwaldvogel/log4j-systemd-journal-appender) but I do not see an option to do that here.

**Comment by satabin** [comment]
Not yet, but I will add it. Thanks for reporting.

**Comment by georgeyanev** [comment]
Great! Is 0.3.0 in the maven repo yet?

**Comment by satabin** [comment]
Not yet, I will tag and publish 0.3.0 tonight (GMT+2).

**Comment by satabin** [comment]
Just pushed 0.3.0 artifacts on sonatype, sorry for the delay. It should by synced with maven central within a few hours.
