### ISSUE TITLE
stacktrace longer than 4096 characters turns into NULL

### ISSUE THREAD

**Issue by aclowkey** [gnieh/logback-journal#13]
I've been playing around with this repo and found that some of my stacktraces are 'null'.
I try using `substring` and found that if it's 4095 it works, and 4096 doesnt.

Is this a systemd limitation? Any tips?

**Comment by aclowkey** [comment]
Turns out it's an issue with my testing. 
I used journalctl --output json to test which gave me EX_STACKTRACE: null, but using --output verbose did shoe the entire value!

**Comment by satabin** [comment]
Hi,

You answered your question too quickly, didn't have a chance to look at it :)

I am glad you solved your problem.
