### ISSUE TITLE
Could not find artifact org.gnieh:logback-journal:jar:0.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by alourie** [gnieh/logback-journal#7]
I'm trying to build a project with logback-journal, but apparently it's not found on maven repo, and the build fails with: <code>Could not find artifact org.gnieh:logback-journal:jar:0.1.0-SNAPSHOT</code>

**Comment by satabin** [comment]
You must add the [snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/) to your repositories in your configuration.

**Comment by alourie** [comment]
@satabin Thanks, that solved this one. But now I have another issue, similar to #1 but with the new lib:
<code>java.lang.UnsatisfiedLinkError: Unable to load library 'systemd-journal': Native library (linux-x86-64/libsystemd-journal.so) not
found in resource path ([...])</code>. Any ideas on what could it be? My platform is debian jessie.

**Comment by satabin** [comment]
Did you install the `-dev` package?

**Comment by bwaldvogel** [comment]
Do you plan to publish a release?

**Comment by satabin** [comment]
It has been a while since no problem was reported on this. I will release it today.

**Comment by satabin** [comment]
I just published version 0.1.0 on sonatype repository. It may require a few hours before it lands on central repository.

**Comment by bwaldvogel** [comment]
Thanks. Works for me.
